=== carmada-dev/demo-images/_schemas/image.schema.json
{
	"$id": "https://raw.githubusercontent.com/carmada-dev/demo-images/main/_schemas/image.scheam.json",
	"$schema": "https://json-schema.org/draft/2020-12/schema",


	"$defs":{
		"gallery": {
			"type": "object",
			"description": "The target gallery to upload the image",
			"properties": {
				"subscription": {
					"$ref": "./_definitions.schema.json#/$defs/guid",
					"description": "The subscription ID of the gallery"
				},
				"resourceGroup": {
					"type": "string",
					"description": "The resource group of the gallery"
				},
				"name": {
					"type": "string",
					"description": "The gallery resource name"
				}
			},
			"required": [ "subscription", "resourceGroup", "name" ],
			"additionalProperties": false
		},
		"archive": {
			"type": "object",
			"description": "The target archive to upload the image in VHDX format",
			"properties": {
				"subscription": {
					"$ref": "./_definitions.schema.json#/$defs/guid",
					"description": "The subscription ID of the archive"
				},
				"resourceGroup": {
					"type": "string",
					"description": "The resource group of the archive"
				},
				"name": {
					"type": "string",
					"description": "The archive storage account resource name",
					"default": ""
				}				
			},
			"required": [ "subscription", "resourceGroup", "name" ],
			"additionalProperties": false
		},
		"devCenter": {
			"type": "object",
			"description": "The target dev center to create a DevBox Definition in",
			"properties": {
				"subscription": {
					"$ref": "./_definitions.schema.json#/$defs/guid",
					"description": "The subscription ID of the dev center"
				},
				"resourceGroup": {
					"type": "string",
					"description": "The resource group of the dev center"
				},
				"name": {
					"type": "string",
					"description": "The dev center resource name"
				},
				"storage": {
					"type": "string",
					"description": "The storage size to use for the DevBox Definition"
				},
				"compute": {
					"type": "string",
					"description": "The compute size to use for the DevBox Definition"
				}
			},
			"required": [ "subscription", "resourceGroup", "name", "storage", "compute" ],
			"additionalProperties": false
		},
		"devDrive": {
			"type": "object",
			"description": "Create a DevDrive inside the image",
			"properties": {
				"sizeGB": {
					"type": "integer",
					"description": "The size of the dev drive in GB (minimum 5GB) - set to 0 to disable DevDrive",
					"minimum": 0,
					"default": 0
				},
				"filters": {
					"type": "array",
					"description": "Filters to apply to the DevDrive",
					"default": [
						"bindFlt",
						"wcifs",
						"PrjFlt",
						"MsSecFlt",
						"WdFilter",
						"FileInfo",
						"ProcMon24",
						"WinSetupMon"
					],
					"items": {
						"type": "string",
						"description": "The name of a filter to apply"
					}
				},
				"repositories": {
					"type": "array",
					"description": "List of repositories to clone into the DevDrive",
					"default": [],
					"items": {
						"type": "object",
						"properties": {
							"repoUrl": {
								"type": "string",
								"description": "The URL of the repository"
							},
							"tokenUrl": {
								"type": "string",
								"description": "An Azure KeyVault secret URL containing the token to access the repository"
							}
						},
						"required": [ "repoUrl" ],
						"additionalProperties": false
					}
				}
			},
			"required": [ "sizeGB", "filters", "repositories" ],
			"additionalProperties": false		
		}
	},


	"title": "Image",
	"description": "DevBox image definition",
	"type": "object",
	"properties": {
		"publisher": {
			"type": "string",
			"description": "The publisher of the image"
		},
		"offer": {
			"type": "string",
			"description": "The offer of the image"
		},
		"sku": {
			"type": "string",
			"description": "The SKU of the image"
		},
		"regions": {
			"type": "array",
			"description": "The regions where the image is available",
			"items": {
				"type": "string"
			}
		},
		"updates": {
			"type": "string",
			"description": "Windows updates that should be installed on the image",
			"enum": [ "all", "none", "recommended", "important" ],
			"default": "all"
		},
		"base": {
			"type": "object",
			"description": "The base image",
			"properties": {
				"publisher": {
					"type": "string",
					"description": "The publisher of the base image"
				},
				"offer": {
					"type": "string",
					"description": "The offer of the base image"
				},
				"sku": {
					"type": "string",
					"description": "The SKU of the base image"
				},
				"version": {
					"type": "string",
					"description": "The version of the base image",
					"default": "latest"
				}
			},
			"required": [ "publisher", "offer", "sku", "version" ],
			"additionalProperties": false
		},
		"gallery": {
			"type": "object",
			"$ref": "#/$defs/gallery"
		},
		"archive": {
			"type": "object",
			"$ref": "#/$defs/archive"
		},
		"devCenter": {
			"type": "object",
			"$ref": "#/$defs/devCenter"
		},
		"devDrive": {
			"type": "object",
			"$ref": "#/$defs/devDrive"
		},
		"features": {
			"type": "array",
			"description": "List of features to enable in the image",
			"default": [],
			"items": {
				"type": "string"
			}
		},
		"prepare": {
			"type": "array",
			"description": "List of scripts to run to prepare the image before installing packages",
			"default": [],
			"items": {
				"type": "string"
			}
		},
		"packages": {
			"type": "array",
			"description": "List of packages to install in the image",
			"default": [],
			"items": {				
				"oneOf": [
					{
						"$ref": "./_definitions.schema.json#/$defs/package"
					},
					{
						"$ref": "./_definitions.schema.json#/$defs/packageRef"
					}
				]
			}
		},
		"configure": {
			"type": "array",
			"description": "List of scripts to run to configure the image after installing packages",
			"default": [],
			"items": {
				"type": "string"
			}
		}
	}
}

=== carmada-dev/demo-images/DockerDesktopWSL/image.json
{
	"$schema": "../_schemas/image.schema.json",

	"publisher": "CarmadaRnD",
	"offer": "CarmadaDev",
	"sku": "win11-dockerdesktop-wsl-devbox",
	"regions": [ "West Europe" ],
	"updates": "none",

	"base": {
		"publisher": "MicrosoftVisualStudio",
		"offer": "windowsplustools",
		"sku": "base-win11-gen2",
		"version": "2024.09.12"
	},
	
	"gallery": {
		"subscription": "f9fcf631-fa8d-4ea2-8298-61b43220a3d1",
		"resourceGroup": "ORG-CarmadaRnD",
		"name": "CarmadaRnD"
	},
	
	"archive": {
		"subscription": "f9fcf631-fa8d-4ea2-8298-61b43220a3d1",
		"resourceGroup": "ORG-CarmadaRnD",
		"name": ""
	},
	
	"devCenter": {
		"subscription": "f9fcf631-fa8d-4ea2-8298-61b43220a3d1",
		"resourceGroup": "ORG-CarmadaRnD",
		"name": "CarmadaRnD",
		"compute": "general_i_8c32gb1024ssd_v2",
		"storage": "ssd_1024gb"
	},
	
	"devDrive": {
		"sizeGB": 0,
		"filters": [],
		"repositories": []
	},

	"features": [

	],

	"prepare": [

	],

	"packages": [
		{
			"name": "dockerDesktopWSL",
			"source": "alias"
		}
	],

	"configure": [

	]
}

=== carmada-dev/demo-images/DataScienceBox/image.json
{
	"$schema": "../_schemas/image.schema.json",

	"publisher": "CarmadaRnD",
	"offer": "CarmadaDev",
	"sku": "win11-datascience-devbox",
	"regions": [ "West Europe" ],
	"updates": "all",
	
	"base": {
		"publisher": "MicrosoftVisualStudio",
		"offer": "windowsplustools",
		"sku": "base-win11-gen2",
		"version": "latest"
	},
	
	"gallery": {
		"subscription": "f9fcf631-fa8d-4ea2-8298-61b43220a3d1",
		"resourceGroup": "ORG-CarmadaRnD",
		"name": "CarmadaRnD"
	},
	
	"archive": {
		"subscription": "f9fcf631-fa8d-4ea2-8298-61b43220a3d1",
		"resourceGroup": "ORG-CarmadaRnD",
		"name": ""
	},
	
	"devCenter": {
		"subscription": "f9fcf631-fa8d-4ea2-8298-61b43220a3d1",
		"resourceGroup": "ORG-CarmadaRnD",
		"name": "CarmadaRnD",
		"compute": "general_i_8c32gb1024ssd_v2",
		"storage": "ssd_1024gb"
	},
	
	"devDrive": {
		"sizeGB": 0,
		"filters": [],
		"repositories": []
	},

	"features": [

	],

	"prepare": [

	],

	"packages": [
		{
			"name": "Microsoft.VisualStudio.2022.Community",
			"scope": "machine",
			"override": [
				"--add", "Microsoft.VisualStudio.Workload.CoreEditor", 
				"--add", "Microsoft.VisualStudio.Workload.Azure", 
				"--add", "Microsoft.VisualStudio.Workload.Data",
				"--add", "Microsoft.VisualStudio.Workload.DataScience",
				"--add", "Microsoft.VisualStudio.Workload.ManagedDesktop", 
				"--add", "Microsoft.VisualStudio.Workload.Node", 
				"--add", "Microsoft.VisualStudio.Workload.Python",
				"--includeRecommended",
				"--installWhileDownloading",
				"--quiet",
				"--norestart",
				"--force",
				"--wait",
				"--nocache"				
			]			
		},
		{
			"name": "vscode",
			"source": "alias"
		},
		{
			"name": "JetBrains.PyCharm.Community",
			"scope": "machine"
		},
		{
			"name": "Microsoft.AzureDataStudio",
			"scope": "machine"
		}
	],

	"configure": [

	]
}

=== carmada-dev/demo-images/MobileBox/image.json
{
	"$schema": "../_schemas/image.schema.json",
	"publisher": "CarmadaRnD",
	"offer": "CarmadaDev",
	"sku": "win11-mobile-devbox",
	"regions": [ "West Europe" ],
	"updates": "all",

	"base": {
		"publisher": "MicrosoftVisualStudio",
		"offer": "windowsplustools",
		"sku": "base-win11-gen2",
		"version": "latest"
	},
	
	"gallery": {
		"subscription": "f9fcf631-fa8d-4ea2-8298-61b43220a3d1",
		"resourceGroup": "ORG-CarmadaRnD",
		"name": "CarmadaRnD"
	},
	
	"archive": {
		"subscription": "f9fcf631-fa8d-4ea2-8298-61b43220a3d1",
		"resourceGroup": "ORG-CarmadaRnD",
		"name": ""
	},
	
	"devCenter": {
		"subscription": "f9fcf631-fa8d-4ea2-8298-61b43220a3d1",
		"resourceGroup": "ORG-CarmadaRnD",
		"name": "CarmadaRnD",
		"compute": "general_i_8c32gb1024ssd_v2",
		"storage": "ssd_1024gb"
	},
	
	"devDrive": {
		"sizeGB": 0,
		"filters": [],
		"repositories": []
	},

	"features": [

	],

	"prepare": [

	],

	"packages": [
		{
			"name": "dockerDesktopWSL",
			"source": "alias"
		},
		{
			"name": "vscode",
			"source": "alias"			
		},
		{
			"name": "Microsoft.VisualStudio.2022.Enterprise",
			"scope": "machine",
			"override": [
				"--add Microsoft.VisualStudio.Workload.CoreEditor", 
				"--add Microsoft.VisualStudio.Workload.NetCrossPlat",
				"--includeRecommended",
				"--includeOptional",
				"--installWhileDownloading",
				"--quiet",
				"--norestart",
				"--force",
				"--wait",
				"--nocache"
			]
		},
		{
			"name": "Google.AndroidStudio",
			"scope": "machine"
		},
		{
			"name": "Wondershare.MirrorGo",
			"scope": "machine"
		},
		{
			"name": "git",
			"source": "alias"
		},
		{
			"name": "GitHub.cli",
			"scope": "machine"
		},
		{
			"name": "GitHub.GitHubDesktop",
			"scope": "machine"
		},
		{
			"name": "Postman.Postman",
			"scope": "user"
		},
		{
			"name": "Microsoft.Azure.StorageExplorer",
			"scope": "machine"
		},
		{
			"name": "Google.Chrome",
			"scope": "machine"
		},
		{
			"name": "Mozilla.Firefox",
			"scope": "machine"
		}
	],

	"configure": [

	]
}

=== carmada-dev/demo-images/Sitecore-1003H-Box/image.json
{
	"$schema": "../_schemas/image.schema.json",
	"publisher": "CarmadaRnD",
	"offer": "CarmadaDev",
	"sku": "win11-sitecore-1003H-devbox",
	"regions": [ "West Europe" ],
	"updates": "all",

	"base": {
		"publisher": "MicrosoftVisualStudio",
		"offer": "windowsplustools",
		"sku": "base-win11-gen2",
		"version": "latest"
	},
	
	"gallery": {
		"subscription": "f9fcf631-fa8d-4ea2-8298-61b43220a3d1",
		"resourceGroup": "ORG-CarmadaRnD",
		"name": "CarmadaRnD"
	},
	
	"archive": {
		"subscription": "f9fcf631-fa8d-4ea2-8298-61b43220a3d1",
		"resourceGroup": "ORG-CarmadaRnD",
		"name": ""
	},
	
	"devCenter": {
		"subscription": "f9fcf631-fa8d-4ea2-8298-61b43220a3d1",
		"resourceGroup": "ORG-CarmadaRnD",
		"name": "CarmadaRnD",
		"compute": "general_i_8c32gb1024ssd_v2",
		"storage": "ssd_1024gb"
	},
	
	"devDrive": {
		"sizeGB": 0,
		"filters": [],
		"repositories": []
	},

	"features": [

	],

	"prepare": [

	],

	"packages": [
		{
			"name": "dockerDesktopHyperV",
			"source": "alias"
		},
		{
			"name": "RedHat.Podman",
			"scope": "machine"			
		},
		{
			"name": "RedHat.Podman-Desktop",
			"scope": "machine"
		}
	],

	"configure": [
		"[IMAGEROOT]/../_scripts/Install-SitecoreXP0-1003H.ps1"
	]
}

=== carmada-dev/demo-images/PodmanBox/image.json
{
	"$schema": "../_schemas/image.schema.json",

	"publisher": "CarmadaRnD",
	"offer": "CarmadaDev",
	"sku": "win11-podman-devbox",
	"regions": [ "West Europe" ],
	"updates": "all",

	"base": {
		"publisher": "MicrosoftVisualStudio",
		"offer": "windowsplustools",
		"sku": "base-win11-gen2",
		"version": "latest"
	},
	
	"gallery": {
		"subscription": "f9fcf631-fa8d-4ea2-8298-61b43220a3d1",
		"resourceGroup": "ORG-CarmadaRnD",
		"name": "CarmadaRnD"
	},
	
	"archive": {
		"subscription": "f9fcf631-fa8d-4ea2-8298-61b43220a3d1",
		"resourceGroup": "ORG-CarmadaRnD",
		"name": ""
	},
	
	"devCenter": {
		"subscription": "f9fcf631-fa8d-4ea2-8298-61b43220a3d1",
		"resourceGroup": "ORG-CarmadaRnD",
		"name": "CarmadaRnD",
		"compute": "general_i_8c32gb1024ssd_v2",
		"storage": "ssd_1024gb"
	},
	
	"devDrive": {
		"sizeGB": 0,
		"filters": [],
		"repositories": []
	},

	"features": [

	],

	"prepare": [

	],

	"packages": [

		{
			"name": "podman-desktop",
			"source": "alias"
		}

	],

	"configure": [

	]
}

=== carmada-dev/demo-images/SitecoreBox/image.json
{
	"$schema": "../_schemas/image.schema.json",
	"publisher": "CarmadaRnD",
	"offer": "CarmadaDev",
	"sku": "win11-sitecore-devbox",
	"regions": [ "West Europe" ],
	"updates": "all",

	"base": {
		"publisher": "MicrosoftVisualStudio",
		"offer": "windowsplustools",
		"sku": "base-win11-gen2",
		"version": "latest"
	},
	
	"gallery": {
		"subscription": "f9fcf631-fa8d-4ea2-8298-61b43220a3d1",
		"resourceGroup": "ORG-CarmadaRnD",
		"name": "CarmadaRnD"
	},
	
	"archive": {
		"subscription": "bffe1654-7f9a-4630-b7b9-d24759a76222",
		"resourceGroup": "BLD-Carmada",
		"name": "carmada"
	},
	
	"devCenter": {
		"subscription": "f9fcf631-fa8d-4ea2-8298-61b43220a3d1",
		"resourceGroup": "ORG-CarmadaRnD",
		"name": "CarmadaRnD",
		"compute": "general_i_8c32gb1024ssd_v2",
		"storage": "ssd_1024gb"
	},
	
	"devDrive": {
		"sizeGB": 0,
		"filters": [],
		"repositories": []
	},

	"features": [

	],

	"prepare": [
		"[IMAGEROOT]/../_scripts/Prepare-Sitecore.ps1"
	],

	"packages": [
		{
			"name": "dockerDesktopWSL",
			"source": "alias"
		}
	],

	"configure": [
		
	]
}

=== carmada-dev/demo-images/DotNetBox/image.json
{
	"$schema": "../_schemas/image.schema.json",

	"publisher": "CarmadaRnD",
	"offer": "CarmadaDev",
	"sku": "win11-dotnet-devbox",
	"regions": [ "West Europe" ],
	"updates": "all",

	"base": {
		"publisher": "MicrosoftVisualStudio",
		"offer": "windowsplustools",
		"sku": "base-win11-gen2",
		"version": "latest"
	},
	
	"gallery": {
		"subscription": "f9fcf631-fa8d-4ea2-8298-61b43220a3d1",
		"resourceGroup": "ORG-CarmadaRnD",
		"name": "CarmadaRnD"
	},
	
	"archive": {
		"subscription": "f9fcf631-fa8d-4ea2-8298-61b43220a3d1",
		"resourceGroup": "ORG-CarmadaRnD",
		"name": ""
	},
	
	"devCenter": {
		"subscription": "f9fcf631-fa8d-4ea2-8298-61b43220a3d1",
		"resourceGroup": "ORG-CarmadaRnD",
		"name": "CarmadaRnD",
		"compute": "general_i_8c32gb1024ssd_v2",
		"storage": "ssd_1024gb"
	},
	
	"devDrive": {
		"sizeGB": 0,
		"filters": [],
		"repositories": []
	},

	"features": [

	],

	"prepare": [

	],

	"packages": [
		{
			"name": "Microsoft.DotNet.SDK.3_1",
			"scope": "machine"
		},
		{
			"name": "Microsoft.DotNet.SDK.5",
			"scope": "machine"
		},
		{
			"name": "Microsoft.DotNet.SDK.6",
			"scope": "machine"
		},
		{
			"name": "Microsoft.DotNet.SDK.7",
			"scope": "machine"
		},
		{
			"name": "vscode",
			"source": "alias"
		},
		{
			"name": "Microsoft.VisualStudio.2022.Enterprise",
			"scope": "machine",
			"override": [
				"--add Microsoft.VisualStudio.Workload.CoreEditor", 
				"--add Microsoft.VisualStudio.Workload.Azure", 
				"--add Microsoft.VisualStudio.Workload.NetCrossPlat",
				"--add Microsoft.VisualStudio.Workload.NetWeb",
				"--add Microsoft.VisualStudio.Workload.Node", 
				"--add Microsoft.VisualStudio.Workload.Python",
				"--add Microsoft.VisualStudio.Workload.ManagedDesktop", 
				"--includeRecommended",
				"--installWhileDownloading",
				"--quiet",
				"--norestart",
				"--force",
				"--wait",
				"--nocache"
			]
		},
		{
			"name": "git",
			"source": "alias"
		},
		{
			"name": "GitHub.cli",
			"scope": "machine"
		},
		{
			"name": "GitHub.GitHubDesktop",
			"scope": "machine"
		},
		{
			"name": "Microsoft.SQLServerManagementStudio",
			"scope": "machine",
			"override": [
				"/install",
				"/quiet",
				"/norestart"
			]
		},
		{
			"name": "dockerDesktopWSL",
			"source": "alias"
		},
		{
			"name": "VideoLAN.VLC",
			"scope": "machine"
		},
		{
			"name": "Microsoft.Bicep",
			"scope": "machine"
		},
		{
			"name": "Microsoft.AzureCLI",
			"scope": "machine"
		},
		{
			"name": "Microsoft.Azure.StorageExplorer",
			"scope": "machine"
		},
		{
			"name": "Microsoft.AzureDataStudio",
			"scope": "machine"
		},
		{
			"name": "Google.Chrome",
			"scope": "machine"
		},
		{
			"name": "Mozilla.Firefox",
			"scope": "machine"
		},
		{
			"name": "Wiesemann-Theis.USB-Redirector",
			"scope": "machine"
		}
	],

	"configure": [
		"[IMAGEROOT]/../_scripts/Install-FabulaTechUSBServer.ps1",
		"[IMAGEROOT]/../_scripts/Install-RadzioModbusMasterSimulator.ps1"
	]
}
